# Generated by Django 4.2 on 2023-04-04 09:54

from django.db import migrations, models
import fileserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('fileserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='guid',
            field=models.CharField(default='65afb09f32dc4e5ba6d80508b8167a2f', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=fileserver.models.upload_path),
        ),
    ]
